/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as DeudasRouteImport } from './routes/deudas'
import { Route as InversionRouteImport } from './routes/inversion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const DeudasRoute = DeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => rootRouteImport,
} as any)
const InversionRoute = InversionRouteImport.update({
  id: '/inversion',
  path: '/inversion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/creditos': typeof CreditosRoute
  '/deudas': typeof DeudasRoute
  '/inversion': typeof InversionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/creditos': typeof CreditosRoute
  '/deudas': typeof DeudasRoute
  '/inversion': typeof InversionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/creditos': typeof CreditosRoute
  '/deudas': typeof DeudasRoute
  '/inversion': typeof InversionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asistente' | '/creditos' | '/deudas' | '/inversion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asistente' | '/creditos' | '/deudas' | '/inversion'
  id: '__root__' | '/' | '/asistente' | '/creditos' | '/deudas' | '/inversion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  CreditosRoute: typeof CreditosRoute
  DeudasRoute: typeof DeudasRoute
  InversionRoute: typeof InversionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deudas': {
      id: '/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof DeudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inversion': {
      id: '/inversion'
      path: '/inversion'
      fullPath: '/inversion'
      preLoaderRoute: typeof InversionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  CreditosRoute: CreditosRoute,
  DeudasRoute: DeudasRoute,
  InversionRoute: InversionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
